
name: Publish main branch to GitHub Pages

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
    contents: read
    pages: write      # to deploy to Pages
    id-token: write   # to verify the deployment originates from an appropriate source
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Clone the source repo
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/flutter-action
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Build the web artifact
        run: |
          flutter doctor -v
          flutter pub get
          flutter test
          flutter build web --base-href / --release

      # https://stackoverflow.com/a/73450467
      - name: Upload the web artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: build/web

  # https://github.com/actions/deploy-pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
